### PR TITLE
mixinsources

### PR DESCRIPTION
**Pull request by mrbatista**
-mixins property in model-config.json support directory;
-Removed backward compatibility with non-camelcase model Readonly;
-Fix style issue;
-Update README.

### CODE REVIEW

**Comment by mrbatista** [comment]
@mrfelton I removed not-camelcase model because loopback during boot automatically converts dashed names (read-only.js) in camel-case. See [this](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file) documentation for more information.

**Comment by mrbatista** [comment]
@mrfelton Would you mind taking a quick look into test [should not change readonly properties with bulk updates](https://github.com/fullcube/loopback-ds-readonly-mixin/blob/mixinsources/test/test-server.js#L105)? Thanks.

**Comment by mrfelton** [comment]
Thanks @mrbatista . I have tried with your changes but still none of the tests pass and I can see no evidence that the mixin is being loaded.

**Comment by mrbatista** [comment]
@mrfelton Sorry, try now.

**Comment by mrfelton** [comment]
Thanks @mrbatista merged and published as v1.0.1.

**Pull request merged**
